name: phydev/SPiCCAto
on:
  push:
    branches:
    - "**/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - run: sudo apt-get update
    - run: sudo apt-get install --reinstall build-essential
    - run: sudo apt-get install gfortran
    - run: make
    - run: "./run-SPiCCAto test -53453 0.2 0.0 0.8 2.0"
    - run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
