name: phydev/SPiCCAto
on:
  push:
    branches:
    - "**/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Install requirements
      run: |
        #echo 'deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list
        #echo 'deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe multiverse"' | sudo tee -a /etc/apt/sources.list
        sudo apt-get update 
        sudo apt-get install gfortran-5
    - name: Make & install
      run: |
        make
        "./run-SPiCCAto test -53453 0.2 0.0 0.8 2.0"
    - name: Retrieve test results
      run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
