name: phydev/SPiCCAto
on:
  push:
    branches:
    - "**/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Install requirements
      run: |
        sudo apt-get update 
        sudo apt-get install gfortran
    - name: Make & install
      run: |
        make
        "./run-SPiCCAto test -53453 0.2 0.0 0.8 2.0"
    - name: Retrieve test results
      run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
